apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-f91d5b156c0d40989d438a1a40f2678d-depl
  labels:
    app: coll-f91d5b156c0d40989d438a1a40f2678d
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-f91d5b156c0d40989d438a1a40f2678d
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-f91d5b156c0d40989d438a1a40f2678d
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-f91d5b156c0d40989d438a1a40f2678d
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-f91d5b156c0d40989d438a1a40f2678d
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping